<?php

namespace Magenest\Movie\Block\System\Config\Form\Field;

use Magento\Framework\Data\Form\Element\AbstractElement;

class Disable extends \Magento\Config\Block\System\Config\Form\Field
{
    private AbstractElement $el;

    protected function _getElementHtml(AbstractElement $element)
    {
        $this->el = $element;
        $element->setDisabled('disabled');
        return $element->getElementHtml();
    }

    protected function _afterToHtml($html)
    {
        $this->el->setDisabled('disabled');
        return $this->el->getElementHtml(); // TODO: Change the autogenerated stub
    }
}
