<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Rating</th>
        <th>Director</th>
    </tr>
    <?php foreach ($block->getProducts() as $product): ?>
        <tr>
            <td><?php echo $product->getName() ?></td>
            <td><?php echo $product->getdescription() ?></td>
            <td><?php echo $product->getrating() ?></td>
            <td><?php echo $product->getdirector_id() ?></td>
        </tr>
    <?php endforeach; ?>
</table>
